// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-NHuUjrRU5RwmmLt5hAWBvBlSrWs1oy0',
    appId: '1:642714833975:web:0fb23137ecbb7dc1675bb2',
    messagingSenderId: '642714833975',
    projectId: 'app-demo-e17a9',
    authDomain: 'app-demo-e17a9.firebaseapp.com',
    storageBucket: 'app-demo-e17a9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgK5JafCWm3xK8WWoEEtk9iTccgJQmVTY',
    appId: '1:642714833975:android:ad911c04ec320cbb675bb2',
    messagingSenderId: '642714833975',
    projectId: 'app-demo-e17a9',
    storageBucket: 'app-demo-e17a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxG8Ltek5sHlGifuZx06nuAmN-mJK1AAo',
    appId: '1:642714833975:ios:d45b31ee4f5d7c9c675bb2',
    messagingSenderId: '642714833975',
    projectId: 'app-demo-e17a9',
    storageBucket: 'app-demo-e17a9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxG8Ltek5sHlGifuZx06nuAmN-mJK1AAo',
    appId: '1:642714833975:ios:d45b31ee4f5d7c9c675bb2',
    messagingSenderId: '642714833975',
    projectId: 'app-demo-e17a9',
    storageBucket: 'app-demo-e17a9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-NHuUjrRU5RwmmLt5hAWBvBlSrWs1oy0',
    appId: '1:642714833975:web:72953b66d76c10d7675bb2',
    messagingSenderId: '642714833975',
    projectId: 'app-demo-e17a9',
    authDomain: 'app-demo-e17a9.firebaseapp.com',
    storageBucket: 'app-demo-e17a9.firebasestorage.app',
  );
}
